[profile.default]
solc = "0.8.17"
optimizer = true
optimizer_runs = 200
revert_strings = "strip"

ffi = true
src = "test"
out = "artifacts/foundry"
script = "scripts"
cache_path = "cache/foundry"
fs_permissions = [{ access = "read", path = "./deployments" }]
verbosity = 3

[profile.production.fuzz]
runs = 66_666

[profile.overkill.fuzz]
runs = 6_666_666
