[profile.default]
solc = "0.8.17"
optimizer = true
optimizer_runs = 200
revert_strings = "strip"

ffi = true
src = "test/solidity"
out = "artifacts/.foundry"
script = "scripts"
cache_path = "cache/.foundry"
fs_permissions = [
  { access = "read", path = "./deployments" },
  { access = "read-write", path = "./cache/.foundry" },
]
verbosity = 3

[profile.default.invariant]
fail_on_revert = true
seed = 0xdeadbeef

[profile.production.fuzz]
runs = 66_666

[profile.production.invariant]
runs = 66_666

[profile.overkill.fuzz]
runs = 6_666_666

[profile.overkill.invariant]
runs = 6_666_666
