on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-25f24e677a6a32a62512ad4f561995589ac2c7dc
      - run: pnpm install --frozen-lockfile
      - uses: changesets/action@v1
        with:
          title: 🔖 new release
          publish: bunx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
