on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPTIMISM_NODE: ${{ secrets.OPTIMISM_NODE }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - uses: foundry-rs/foundry-toolchain@v1
      - run: yarn
      - run: yarn lint
      - run: forge build
      - run: yarn coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info,coverage/lcov.info
